---
- name: Display Role Details.
  debug:
    msg:
      - '====================================================================='
      - 'constrict0r.basik'
      - 'Setup basic Debian-like systems.'
      - '====================================================================='
